### ISSUE TITLE
Saving after changing of Process Id is not possible

### ISSUE THREAD

**Issue by SORC3r3r** [process-engine/charon#31] opened 2017-10-21 10:48 UTC
#### Describe your issue

After accidentally creating a process with the same 'key' as an already existing process, I tried to change the 'key' by selecting the participant and editing the field 'Process Id' which contains the 'key'.
Unfortunately after editing the 'Process Id' field, I am not able to save the model.

I wanted to change the key because by starting the new process, the other process with the same key started and the tasks of the first created process were displayed.

#### How can others reproduce the issue?

1. create a process 
2. select the process
3. select the participant 
4. edit the 'Process Id'
5. try saving the process

[optional]
1. create a process with key 'start'
2. create a user task in the process (uiName-Confirm)
3. create another process with the same key
4. create a user task in the newly created process which differs from the user task in the first process.
5. start the second created process and see the user task of the first created process displayed

#### What's your setup

- OS (`Windows/OS X/Linux` + `version`): Ubuntu 17
- Node (`node --version`): 7.10.1
- NPM (`npm --version`): 4.2.0
- Docker (`docker version --format '{{.Server.Version}}'`):
- Firefox/Chrome

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

![changing_processid](https://user-images.githubusercontent.com/22958825/31851103-31abfede-b65f-11e7-9dc9-f7febf36ac45.png)

**Comment by Paulomart** [comment] 2017-10-26 12:15
I found the cause of the problem:

There are two points there the key is stored:
- In the ProcessDefEntity
- In the XML Diagram of the ProcessDefEntity

Normally there match.

The key displayed in the editor is extracted from the the xml diagram. When you change the key in the editor charon calls the `/ProcessDef/:id/updateBpmn` method of the datastore. In this method the processengine searches all defined processes in the diagram using the key stored in the ProcessDefEntity. When there is no process defined in the xml matching the stored process an error raises: https://github.com/process-engine/process_engine/blob/develop/src/entity_types/process_def.ts#L390.

To solve this issue we can do three things:

1. Update the ProcessDefEntity key in advance using the datastore and then all the `updateBpmn` route.
2. Change the behavior of the `updateBpmn` route when there is only one process in the xml to _always_ take that process and update the ProcessDefEntity key
3. Create a new route to rename processes.

**Comment by ppoetschke** [comment] 2017-10-26 12:28
Unfortunately it's possible to have multiple processes (pools) in a BPMN file. We don't have a concept yet how we this want to implement.
So as first step I would suggest proposal 2. Basically if the key of a process is renamed (what can always be done), the process has to be created with new new key from scratch and after importing the whole bpmn orphaned processes have to be removed.

**Comment by Paulomart** [comment] 2017-10-26 13:32
Fixed via https://github.com/process-engine/process_engine/commit/c095dfb92279fc30447d9e9dcdc990e17ae3636c.

**Closed by Paulomart** 2017-10-26 13:32 UTC
Labels: bug
